src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $blog_title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $blog_description = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Images $image = null;

    #[ORM\Column(length: 255)]
    private ?string $blog_slug = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBlogTitle(): ?string
    {
        return $this->blog_title;
    }

    public function setBlogTitle(string $blog_title): static
    {
        $this->blog_title = $blog_title;

        return $this;
    }

    public function getBlogDescription(): ?string
    {
        return $this->blog_description;
    }

    public function setBlogDescription(string $blog_description): static
    {
        $this->blog_description = $blog_description;

        return $this;
    }

    public function getImage(): ?Images
    {
        return $this->image;
    }

    public function setImage(?Images $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getBlogSlug(): ?string
    {
        return $this->blog_slug;
    }

    public function setBlogSlug(string $blog_slug): static
    {
        $this->blog_slug = $blog_slug;

        return $this;
    }
}

src/Entity/Images.php
<?php

namespace App\Entity;

use App\Repository\ImagesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImagesRepository::class)]
class Images
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $image_name = null;

    #[ORM\ManyToOne(inversedBy: 'images')]
    private ?TourPackage $tourPackage = null;

    #[ORM\ManyToOne(inversedBy: 'images')]
    private ?HotelsInBhutan $hotelsInBhutan = null;

    #[ORM\ManyToOne(inversedBy: 'image')]
    private ?TopDestination $topDestination = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImageName(): ?string
    {
        return $this->image_name;
    }

    public function setImageName(string $image_name): static
    {
        $this->image_name = $image_name;

        return $this;
    }

    public function getTourPackage(): ?TourPackage
    {
        return $this->tourPackage;
    }

    public function setTourPackage(?TourPackage $tourPackage): static
    {
        $this->tourPackage = $tourPackage;

        return $this;
    }

    public function getHotelsInBhutan(): ?HotelsInBhutan
    {
        return $this->hotelsInBhutan;
    }

    public function setHotelsInBhutan(?HotelsInBhutan $hotelsInBhutan): static
    {
        $this->hotelsInBhutan = $hotelsInBhutan;

        return $this;
    }

    public function getTopDestination(): ?TopDestination
    {
        return $this->topDestination;
    }

    public function setTopDestination(?TopDestination $topDestination): static
    {
        $this->topDestination = $topDestination;

        return $this;
    }
}

src/Entity/Itinerary.php
<?php

namespace App\Entity;

use App\Repository\ItineraryRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ItineraryRepository::class)]
class Itinerary
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $itinerary_description = null;

    #[ORM\ManyToOne(inversedBy: 'itinerary')]
    private ?TourPackage $tourPackage = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getItineraryDescription(): ?string
    {
        return $this->itinerary_description;
    }

    public function setItineraryDescription(string $itinerary_description): static
    {
        $this->itinerary_description = $itinerary_description;

        return $this;
    }

    public function getTourPackage(): ?TourPackage
    {
        return $this->tourPackage;
    }

    public function setTourPackage(?TourPackage $tourPackage): static
    {
        $this->tourPackage = $tourPackage;

        return $this;
    }
}

src/Entity/TravelInfo.php
<?php

namespace App\Entity;

use App\Repository\TravelInfoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TravelInfoRepository::class)]
class TravelInfo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $travel_info_title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $travel_info_description = null;

    #[ORM\ManyToOne(inversedBy: 'travel_info')]
    private ?TravelInfoCategory $travelInfoCategory = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTravelInfoTitle(): ?string
    {
        return $this->travel_info_title;
    }

    public function setTravelInfoTitle(string $travel_info_title): static
    {
        $this->travel_info_title = $travel_info_title;

        return $this;
    }

    public function getTravelInfoDescription(): ?string
    {
        return $this->travel_info_description;
    }

    public function setTravelInfoDescription(string $travel_info_description): static
    {
        $this->travel_info_description = $travel_info_description;

        return $this;
    }

    public function getTravelInfoCategory(): ?TravelInfoCategory
    {
        return $this->travelInfoCategory;
    }

    public function setTravelInfoCategory(?TravelInfoCategory $travelInfoCategory): static
    {
        $this->travelInfoCategory = $travelInfoCategory;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Entity\Bookings;
use App\Entity\HotelsInBhutan;
use App\Entity\TopDestination;
use App\Entity\TourCategory;
use App\Entity\TourPackage;
use App\Entity\TravelInfo;
use App\Entity\TravelInfoCategory;
use App\Enum\TravelInfoEnum;
use App\Form\BookingType;
use App\Form\ContactType;
use App\Service\CategoryService;
use App\Service\ContactValidation;
use App\Service\SendEmail;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Knp\Component\Pager\PaginatorInterface;

ini_set('memory_limit', '256M');

class MainController extends AbstractController
{
    public function __construct(private EntityManagerInterface $em)
    {

    }

    #[Route('/', name: 'app_main')]
    public function index(CategoryService $categoryService): Response
    {
        $tour_packages = $this->em->getRepository(TourPackage::class)->findTourPackages();
        $top_destinations = $this->em->getRepository(TopDestination::class)->findAll();
        $tour_packages_all = $this->em->getRepository(TourPackage::class)->findAll();
        $categories = $this->em->getRepository(TourCategory::class)->findAll();
        return $this->render('main/index.html.twig', [
            'tour_packages' => $tour_packages,
            'top_destinations' => $top_destinations,
            'tour_packages_all' => $tour_packages_all,
            'best_selling_packages' => $categoryService->parentCategoryTours($categories)
        ]);
    }

    #[Route('/tour-packages/{page}', name: 'tour-packages', requirements: ['page' => '\d+'], defaults: ['page' => 1])]
    public function tourPackages(CategoryService $categoryService, PaginatorInterface $paginator, $page)
    {
        $categories = $this->em->getRepository(TourCategory::class)->findAll();
        $bestSellingPackages = $categoryService->parentCategoryTours($categories);

        $pagination = $paginator->paginate(
            $bestSellingPackages['tour_categories'], /* query NOT result */
            $page, /* page number */
            9 /* limit per page */
        );
        return $this->render('main/tour-packages.html.twig', [
            'best_selling_packages' => $pagination
        ]);
    }

    #[Route('/tour/{slug}', name: 'tour-package')]
    public function tourPackage($slug)
    {
        $tours = [];
        $image_name = '';
        $category = $this->em->getRepository(TourCategory::class)->findBy(['slug' => $slug]);

        foreach ($category[0]->getTourCategories() as $tourCategories) {
            if ($tourCategories) {
                foreach ($tourCategories->getTourPackage() as $package) {
                    $tours[$package->getId()] = $package;
                    foreach ($package->getImages() as $image) {
                        if ($image) {
                            $image_name = $image->getImageName();
                        }
                    }
                }
            }
        }
        return $this->render('main/tour-package.html.twig', [
            'tours' => $tours,
            'tour_category' => $category[0]->getCategory(),
            'tour_category_slug' => $slug,
            'image_name' => $image_name
        ]);
    }

    #[Route('/tour/{category}/{slug}', name: 'view-tours')]
    public function viewTours($slug): Response
    {
        $tour_package = $this->em->getRepository(TourPackage::class)->findBy(['tour_title_slug' => $slug]);

        return $this->render('main/view-tours.html.twig', [
            'tour_packages' => $tour_package[0]
        ]);
    }

    #[Route('/blogs/{page}', name: 'blog', requirements: ['page' => '\d+'], defaults: ['page' => 1])]
    public function blog(PaginatorInterface $paginator, $page): Response
    {
        $blogs = $this->em->getRepository(Blog::class)->findAll();
        $pagination = $paginator->paginate(
            $blogs, /* query NOT result */
            $page, /* page number */
            6 /* limit per page */
        );
        return $this->render('main/blogs.html.twig', [
            'blogs' => $pagination
        ]);
    }

    #[Route('/blog/{id}-{slug}', name: 'view-blog')]
    public function viewblog(Blog $blog, $id): Response
    {
        $limit = 10;
        $blogs = $this->em->getRepository(Blog::class)->findBlogs($limit);
        $base_url = 'https://www.'.$_SERVER['HTTP_HOST'];
        $blog_url = $base_url.'/blog/'.$id.'-'.$blog->getBlogSlug();
        return $this->render('main/view-blog.html.twig', [
            'blog' => $blog,
            'blog_url' => $blog_url,
            'blogs' => $blogs,
            'base_url' => $base_url
        ]);
    }

    #[Route('/about-us', name: 'about-us')]
    public function aboutUs(): Response
    {
        return $this->render('main/about.html.twig');
    }

    #[Route('/travel-and-visa', name: 'travel-and-visa')]
    public function travelAndVisa(): Response
    {
        $travelVisaCategory = $this->em->getRepository(TravelInfoCategory::class)->findOneBy(['travel_info_category_name' => TravelInfoEnum::TRAVEL_AND_VISA->value]);
        return $this->render('main/travel_and_visa.html.twig', [
            'travelVisas' => $travelVisaCategory->getTravelInfo()
        ]);
    }

    #[Route('/faqs-and-raqs', name: 'faqs-and-raqs')]
    public function faqsAndRaqs(): Response
    {
        $faqsRaqsCategory = $this->em->getRepository(TravelInfoCategory::class)->findOneBy(['travel_info_category_name' => TravelInfoEnum::FAQS_AND_RAQS->value]);
        return $this->render('main/faqs.html.twig', [
            'faqsRaqs' => $faqsRaqsCategory->getTravelInfo()
        ]);
    }

    #[Route('/about-bhutan', name: 'about-bhutan')]
    public function aboutBhutan()
    {
        return $this->render('main/about-bhutan.html.twig');
    }

    #[Route('/getting-into-bhutan', name: 'getting-into-bhutan')]
    public function gettingIntoBhutan()
    {
        return $this->render('main/getting-into-bhutan.html.twig');
    }

    #[Route('/top-destination/{slug}', name: 'top-destination')]
    public function topDestination($slug)
    {
        $topDestination = $this->em->getRepository(TopDestination::class)->findOneBy(['slug' => $slug]);
        return $this->render('main/top-destinations.html.twig', ['topDestination' => $topDestination ]);
    }

    #[Route('/hotels-in-bhutan', name: 'hotels-in-bhutan-front')]
    public function hotelsInBhutan()
    {
        $hotelsInBhutan = $this->em->getRepository(HotelsInBhutan::class)->findAll();
        return $this->render('main/hotels-in-bhutan.html.twig', [
            'hotelsInBhutan' => $hotelsInBhutan
        ]);
    }

    #[Route('/hotels/{slug}', name: 'hotel-in-bhutan')]
    public function hotelInBhutan($slug)
    {
        $hotelInBhutan = $this->em->getRepository(HotelsInBhutan::class)->findOneBy(['slug' => $slug]);
        $hotelsInBhutan = $this->em->getRepository(HotelsInBhutan::class)->findAll();
        return $this->render('main/hotel-in-bhutan.html.twig', [
            'hotelInBhutan' => $hotelInBhutan,
            'hotelsInBhutan' => $hotelsInBhutan
        ]);
    }

    #[Route('/contact-us', name: 'contact-us')]
    public function contactUs(Request $request, SendEmail $emailService, ContactValidation $validation)
    {
        $form = $this->createForm(ContactType::class, null);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            dd($validation->getErrors($form->getData()));
            //$emailService->sendEmail($form->getData(), 'contact');
        }
        return $this->render('main/contact.html.twig', ['form' => $form]);
    }

    #[Route('/trip-planner', name: 'trip-planner')]
    public function tripPlanner()
    {
        return $this->render('main/trip-planner.html.twig');
    }

    public function _tourCategories($packages_route)
    {
        $mainCategory = [];
        $tourCategories = $this->em->getRepository(TourCategory::class)->findAll();
        $currentRoute = false;
        foreach ($tourCategories as $tourCategory) {
            
            if($tourCategory->getSlug() == $packages_route) {
                $mainCategory[$tourCategory->getId()]['is_current_route'] = true;
            } 
            if ($tourCategory->getSubCategory() == null) {
                $mainCategory[$tourCategory->getId()]['category'] = $tourCategory->getCategory();
                $mainCategory[$tourCategory->getId()]['slug'] = $tourCategory->getSlug();
            }
        }
        return $this->render('main/pages/_packages.html.twig', [
            'categories' => $mainCategory,
        ]);
    }
}

templates/main/blogs.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
<link href="{{ asset('/css/swiffy-slider.min.css')}}" rel="stylesheet" />
<style>
    #blog-view-img {
        background-image: url('{{ asset("/images/image-static/blog.jpg")}}');
        height: 450px;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        width: 100%;
        position: relative;
    }

    #blog-view-header {
        position: absolute;
        background-color: rgba(0, 0, 0, 0.5);
        height: 100%;
        width: 100%;
    }

    #blog-view-header div div h2 {
        color: white;
    }
    
    @media (max-width: 414px) {
        #blog-view-img {
            height: 150px;
            background-attachment:scroll;
        }
    }
</style>
{% endblock %}
{% block body %}
<div id="blog-view-img">
    <div id="blog-view-header">
        <div class="d-flex align-items-center  h-100">
            <div class="container">
                <h2 class="d-inline-flex text-white animated-text-header"><b>OUR BLOG</b></h2>
                <nav aria-label="breadcrumb" class="mt-3">
                    <ol class="breadcrumb bg-orange d-inline-flex ps-1 pe-3">
                        <li class="breadcrumb-item"><a href="/" class="text-white">Home</a></li>
                        <li class="breadcrumb-item"><a class="text-white">Our blog</a></li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5">
    <div class="row">
        {% for blog in blogs %}
        <div class="col-md-4 mt-3 mb-3">
            <a href="{{ path('view-blog',{'id' : blog.id, 'slug' : blog.blogSlug })}}">
                <div class="card card-box-shadow rounded-0">
                    <img src="{{ asset(asset('uploads/images/'~ blog.image.imageName)|imagine_filter('thumbnail_blog')) }}">
                    <div class="card-body">
                        <b>{{ blog.blogTitle}}</b>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
        <div class="navigation" style="z-index: 0;">
            {{ knp_pagination_render(blogs) }}
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
{% endblock %}

templates/main/faqs.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
<style>
    #faqs-raqs-img {
        background-image: url('{{ asset("/images/image-static/kyichu-lhakhang.jpg")}}');
        height: 450px;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        width: 100%;
        position: relative;
    }

    #faqs-raqs-header {
        position: absolute;
        background-color: rgba(0, 0, 0, 0.5);
        height: 100%;
        width: 100%;
    }

    #faqs-raqs-header div div h2 {
        color: white;
    }

    @media (max-width: 414px) {
        #faqs-raqs-img {
            height: 150px;
            background-attachment: scroll;
        }
    }
</style>
{% endblock %}
{% block body %}
<div id="faqs-raqs-img">
    <div id="faqs-raqs-header">
        <div class="d-flex align-items-center h-100">
            <div class="container">
                <h2 class="d-inline-flex text-white animated-text-header"><b>FAQS & RAQS</b></h2>
                <nav aria-label="breadcrumb" class="mt-3">
                    <ol class="breadcrumb bg-orange d-inline-flex ps-1 pe-3">
                        <li class="breadcrumb-item"><a href="/" class="text-white">Home</a></li>
                        <li class="breadcrumb-item"><a class="text-white">Faq's & Raq's</a></li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="mt-5 pt-5 pb-5 bg-orange">
    <div class="container">
        {% for faqRaq in faqsRaqs %}
        <div class="accordion" id="faq-raq-{{ loop.index }}">
            <div class="accordion-item rounded-0">
                <h2 class="accordion-header" id="heading-{{ loop.index }}">
                    <button data-mdb-collapse-init class="accordion-button text-orange" type="button"
                        data-mdb-target="#collapse-{{ loop.index }}" aria-expanded="true"
                        aria-controls="collapse-{{ loop.index }}">
                        <b>{{ faqRaq.travelInfoTitle }}</b>
                    </button>
                </h2>
                <div id="collapse-{{ loop.index }}" class="accordion-collapse collapse"
                    aria-labelledby="heading-{{ loop.index }}" data-mdb-parent="#faq_raq">
                    <div class="accordion-body bg-dark text-white">
                        {{ faqRaq.travelInfoDescription|raw }}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="mt-3 text-center text-white">
            <b>Didn't find the question or answer you were looking for?</b> <a href="/contact-us"
                class="btn btn-danger btn-rounded">CONTACT
                US</a>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
{% endblock %}

templates/main/hotels-in-bhutan.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
<link href="{{ asset('/css/swiffy-slider.min.css')}}" rel="stylesheet" />
<style>
    #hotels-in-bhutan-img {
        background-image: url('{{ asset("/images/image-static/hotel.jpg")}}');
        height: 450px;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        width: 100%;
        position: relative;
    }

    #hotels-in-bhutan-header {
        position: absolute;
        background-color: rgba(0, 0, 0, 0.5);
        height: 100%;
        width: 100%;
    }

    #hotels-in-bhutan-header div div h2 {
        color: white;
    }
    
    @media (max-width: 414px) {
        #hotels-in-bhutan-img {
            height: 150px;
            background-attachment:scroll;
        }
    }
</style>
{% endblock %}
{% block body %}
<div id="hotels-in-bhutan-img">
    <div id="hotels-in-bhutan-header">
        <div class="d-flex align-items-center  h-100">
            <div class="container">
                <h2 class="d-inline-flex text-white animated-text-header"><b>HOTELS IN BHUTAN</b></h2>
                <nav aria-label="breadcrumb" class="mt-3">
                    <ol class="breadcrumb bg-orange d-inline-flex ps-1 pe-3">
                        <li class="breadcrumb-item"><a href="/" class="text-white">Home</a></li>
                        <li class="breadcrumb-item"><a class="text-white">Hotels in Bhutan</a></li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5">
    <div class="row">
        {% for hotel in hotelsInBhutan %}
        <div class="col-md-4 mt-3">
            <a href="{{ path('hotel-in-bhutan',{'slug' : hotel.slug })}}">
                <div class="card card-box-shadow p-2">
                    <img src="{{ asset(asset('uploads/images/'~ hotel.images[0].imageName))|imagine_filter('thumbnail_hotel') }}" class="card-img">
                    <div class="p-2 mt-2">
                        <div>
                            <span><i class="fa-solid fa-star text-orange"></i> {{
                                hotel.ratings}} STARS</span>
                        </div>
                        <div class="mt-2">
                            <b>{{ hotel.hotelName}}</b>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block javascripts %}
{% endblock %}

templates/main/top-destinations.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
<style>
    #top-destinations-img {
        background-image: url('{{ asset("images/image-static/dragon-nest.jpg")}}');
        height: 450px;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        width: 100%;
        position: relative;
    }

    #top-destinations-header {
        position: absolute;
        background-color: rgba(0, 0, 0, 0.5);
        height: 100%;
        width: 100%;
    }

    #top-destinations-header div div h2 {
        color: white;
    }
    
    @media (max-width: 414px) {
        #top-destinations-img {
            height: 150px;
            background-attachment:scroll;
        }
    }
</style>
{% endblock %}
{% block body %}
<div id="top-destinations-img">
    <div id="top-destinations-header">
        <div class="d-flex align-items-center  h-100">
            <div class="container">
                <h2 class="d-inline-flex text-white animated-text-header"><b>TOP DESTINATIONS</b></h2>
                <nav aria-label="breadcrumb" class="mt-3">
                    <ol class="breadcrumb bg-orange d-inline-flex ps-1 pe-3">
                        <li class="breadcrumb-item"><a href="/" class="text-white">Home</a></li>
                        <li class="breadcrumb-item"><a class="text-white">Top destinations</a></li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5">
    {# {% for topDestination in topDestinations %} #}
    <div class="row pt-2 pb-2 mt-3" id="{{ topDestination.destinationTitle|lower|slug }}">
        <div class="col-md-4">
            <img src="{{ asset('uploads/images/'~ topDestination.image.imageName )}}" class="img-fluid">
        </div>
        <div class="col-md-8 d-flex align-items-center">
            <div class="">
                <h4 class="text-orange">{{ topDestination.destinationTitle}} </h4>
                <p>{{ topDestination.description|raw }}</p>
            </div>
        </div>
    </div>
    {# {% endfor %} #}
</div>
{% endblock %}

{% block javascripts %}
{% endblock %}

templates/main/view-blog.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
<link href="{{ asset('/css/swiffy-slider.min.css')}}" rel="stylesheet" />
<style>
    #blog-view-img {
        background-image: url('{{ asset("/uploads/images/"~ blog.image.imageName)}}');
        height: 450px;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        width: 100%;
        position: relative;
    }

    #blog-view-header {
        position: absolute;
        background-color: rgba(0, 0, 0, 0.5);
        height: 100%;
        width: 100%;
    }

    #blog-view-header div div h2 {
        color: white;
    }

    @media (max-width: 414px) {
        #blog-view-img {
            height: 150px;
            background-attachment:scroll;
        }
    }

    /* Container for vertical marquee */
    .marquee-vertical {
        overflow: hidden;
        height: 200px; /* Set the height to show a few items at a time */
        width: 100%; /* Adjust as needed */
        position: relative;
    }

    .marquee-content {
        display: flex;
        flex-direction: column;
        animation: marqueeUp 15s linear infinite;
    }

    .item {
        display: flex;
    }

    /* Keyframes for vertical marquee effect */
    @keyframes marqueeUp {
        0% {
            transform: translateY(0);
        }
        100% {
            transform: translateY(-50%);
        }
    }
</style>
{% endblock %}
{% block meta_property %}
<!-- Facebook -->
<meta property="og:title" content="{{ blog.blogTitle }}" />
<meta property="og:image" content="{{base_url}}{{ asset("/uploads/images/"~ blog.image.imageName)}}" />
<meta property="og:url" content="{{ blog_url }}" />
<meta property="og:site_name" content="{{ base_url }}" />
<meta property="og:type" content="article" />
{% endblock %}
{% block body %}
<div id="blog-view-img">
    <div id="blog-view-header">
        <div class="d-flex align-items-center  h-100">
            <div class="container">
                <h4 class="d-inline-flex text-white text-shadow-orange p-2">{{ blog.blogTitle|upper}}</h4>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-9">
            <div class="mb-3 mt-3">
                {{ include('main/pages/_social_sharer.html.twig',) }}
            </div>
            {{ blog.blogDescription|raw}}
        </div>
        <div class="col-md-3">
            <div class="bg-orange p-2">
                <b class="text-white">LATEST BLOG</b>
            </div>
            <div class="marquee-vertical">
                <div class="marquee-content">
                    {% for blog in blogs %}
                    <div class="blog-card-box-shadow mt-2">
                        <a href="{{ path('view-blog',{'id' : blog.id, 'slug' : blog.blogSlug })}}" class="nav-link">
                            <div class="d-flex item">
                                <div class="p-2 flex-shrink-1">
                                    <img src="{{ asset("/uploads/images/"~ blog.image.imageName)}}" class="img-fluid"
                                        width="100">
                                </div>
                                <div class="p-2 w-100 font-size-12">{{ blog.blogTitle}}</div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
{% endblock %}